[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    # Access-Control-Allow-Origin = "*"
    # Access-Control-Allow-Headers = "Content-Type"
    # Access-Control-Allow-Methods = "GET, HEAD"
    Cache-Control = "no-cache, no-store, must-revalidate"
    x-powered-by = "Clovis Junior"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200