[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    x-powered-by = "Clovis Junior"

[[headers]]
  for = "/player/*"
  [headers.values]
    access-control-allow-headers = "*"
    access-control-allow-methods = "*"
    access-control-allow-origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200